<?php

use Illuminate\Database\Seeder;

class CmsApicustomTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_apicustom')->delete();
        
        \DB::table('cms_apicustom')->insert(array (
            0 => 
            array (
                'id' => 1,
                'permalink' => 'get_departmnets',
                'tabel' => 'departments',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'get departmnets',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:2:{i:0;a:5:{s:4:"name";s:8:"parentid";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:10:"company_id";s:4:"type";s:7:"integer";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:5:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:13:"visiblity_for";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:8:"parentid";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:10:"company_id";s:4:"type";s:7:"integer";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            1 => 
            array (
                'id' => 2,
                'permalink' => 'list_departments',
                'tabel' => 'departments',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'list departments',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:1:{i:0;a:5:{s:4:"name";s:10:"company_id";s:4:"type";s:7:"integer";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:5:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:13:"visiblity_for";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:8:"parentid";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:10:"company_id";s:4:"type";s:7:"integer";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            2 => 
            array (
                'id' => 3,
                'permalink' => 'registration',
                'tabel' => 'companies',
                'aksi' => 'save_add',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Registration',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'post',
                'parameters' => 'a:17:{i:0;a:5:{s:4:"name";s:8:"jobtitle";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:1;a:5:{s:4:"name";s:12:"company_name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:2;a:5:{s:4:"name";s:8:"industry";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:3;a:5:{s:4:"name";s:15:"no_of_employees";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:4;a:5:{s:4:"name";s:15:"company_contact";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:5;a:5:{s:4:"name";s:15:"company_address";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:6;a:5:{s:4:"name";s:12:"country_code";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:7;a:5:{s:4:"name";s:7:"country";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:8;a:5:{s:4:"name";s:5:"state";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:9;a:5:{s:4:"name";s:4:"city";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:10;a:5:{s:4:"name";s:6:"status";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:11;a:5:{s:4:"name";s:10:"first_name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:12;a:5:{s:4:"name";s:11:"middle_name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:13;a:5:{s:4:"name";s:9:"last_name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:14;a:5:{s:4:"name";s:5:"email";s:4:"type";s:5:"email";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:15;a:5:{s:4:"name";s:6:"mobile";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:16;a:5:{s:4:"name";s:8:"password";s:4:"type";s:8:"password";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}}',
                'responses' => 'a:0:{}',
            ),
            3 => 
            array (
                'id' => 4,
                'permalink' => 'testimonial',
                'tabel' => 'testimonial',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => 'status=1',
                'nama' => 'testimonial',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:4:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"0";}i:3;a:5:{s:4:"name";s:5:"image";s:4:"type";s:5:"image";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:6:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:5:"image";s:4:"type";s:5:"image";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:6:"status";s:4:"type";s:7:"tinyint";s:8:"subquery";N;s:4:"used";s:1:"1";}i:5;a:4:{s:4:"name";s:10:"company_id";s:4:"type";s:7:"integer";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            4 => 
            array (
                'id' => 5,
                'permalink' => 'features',
                'tabel' => 'feature',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'features',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:5:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:5:"image";s:4:"type";s:5:"image";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:3;a:5:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:4;a:5:{s:4:"name";s:6:"status";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:5:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:5:"image";s:4:"type";s:5:"image";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:6:"status";s:4:"type";s:7:"tinyint";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            5 => 
            array (
                'id' => 6,
                'permalink' => 'blog',
                'tabel' => 'blog',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Blog',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:5:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:3;a:5:{s:4:"name";s:5:"image";s:4:"type";s:5:"image";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:4;a:5:{s:4:"name";s:6:"status";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:5:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:5:"image";s:4:"type";s:5:"image";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:6:"status";s:4:"type";s:7:"tinyint";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            6 => 
            array (
                'id' => 7,
                'permalink' => 'productroadmap',
                'tabel' => 'productroadmap',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Productroadmap',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:4:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:3;a:5:{s:4:"name";s:6:"status";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:4:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:6:"status";s:4:"type";s:7:"tinyint";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            7 => 
            array (
                'id' => 8,
                'permalink' => 'whitepaper',
                'tabel' => 'whitepaper',
                'aksi' => 'save_add',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Whitepaper',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'post',
                'parameters' => 'a:4:{i:0;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:1;a:5:{s:4:"name";s:5:"email";s:4:"type";s:5:"email";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:2;a:5:{s:4:"name";s:7:"company";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:3;a:5:{s:4:"name";s:7:"website";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}}',
                'responses' => 'a:1:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            8 => 
            array (
                'id' => 9,
                'permalink' => 'career',
                'tabel' => 'career',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'career',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:4:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:3;a:5:{s:4:"name";s:6:"status";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:4:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:11:"description";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:6:"status";s:4:"type";s:7:"tinyint";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            9 => 
            array (
                'id' => 10,
                'permalink' => 'contactus',
                'tabel' => 'contact',
                'aksi' => 'save_add',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Contactus',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'post',
                'parameters' => 'a:5:{i:0;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:1;a:5:{s:4:"name";s:5:"email";s:4:"type";s:5:"email";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:2;a:5:{s:4:"name";s:6:"mobile";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:3;a:5:{s:4:"name";s:11:"countrycode";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:4;a:5:{s:4:"name";s:7:"message";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}}',
                'responses' => 'a:1:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            10 => 
            array (
                'id' => 11,
                'permalink' => 'faqcategory',
                'tabel' => 'faqcategory',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'faqcategory',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:2:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:2:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            11 => 
            array (
                'id' => 12,
                'permalink' => 'faqsubcategory',
                'tabel' => 'faqsubcategory',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'faqsubcategory',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:3:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:13:"faqcategoryid";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:3:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:13:"faqcategoryid";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            12 => 
            array (
                'id' => 13,
                'permalink' => 'faq',
                'tabel' => 'faq',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Faq',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:5:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:13:"faqcategoryid";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:2;a:5:{s:4:"name";s:16:"faqsubcategoryid";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:3;a:5:{s:4:"name";s:8:"question";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:4;a:5:{s:4:"name";s:6:"answer";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:5:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:13:"faqcategoryid";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:16:"faqsubcategoryid";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:8:"question";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:6:"answer";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            13 => 
            array (
                'id' => 15,
                'permalink' => 'hrindexform',
                'tabel' => 'hrindex_form',
                'aksi' => 'save_add',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'hrindexform',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'post',
                'parameters' => 'a:6:{i:0;a:5:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:1;a:5:{s:4:"name";s:5:"email";s:4:"type";s:5:"email";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:2;a:5:{s:4:"name";s:6:"mobile";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:3;a:5:{s:4:"name";s:11:"designation";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:4;a:5:{s:4:"name";s:11:"companyname";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}i:5;a:5:{s:4:"name";s:8:"industry";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"1";s:4:"used";s:1:"1";}}',
                'responses' => 'a:7:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:4:"name";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:2;a:4:{s:4:"name";s:5:"email";s:4:"type";s:5:"email";s:8:"subquery";N;s:4:"used";s:1:"1";}i:3;a:4:{s:4:"name";s:6:"mobile";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:4;a:4:{s:4:"name";s:11:"designation";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}i:5;a:4:{s:4:"name";s:11:"companyname";s:4:"type";s:10:"mediumtext";s:8:"subquery";N;s:4:"used";s:1:"1";}i:6;a:4:{s:4:"name";s:8:"industry";s:4:"type";s:10:"mediumtext";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
            14 => 
            array (
                'id' => 16,
                'permalink' => 'hr_index_question_type',
                'tabel' => 'hrindex_question_type',
                'aksi' => 'list',
                'kolom' => NULL,
                'orderby' => NULL,
                'sub_query_1' => NULL,
                'sql_where' => NULL,
                'nama' => 'Hr Index Question Type',
                'keterangan' => NULL,
                'parameter' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'method_type' => 'get',
                'parameters' => 'a:2:{i:0;a:5:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}i:1;a:5:{s:4:"name";s:13:"question_type";s:4:"type";s:6:"string";s:6:"config";N;s:8:"required";s:1:"0";s:4:"used";s:1:"0";}}',
                'responses' => 'a:2:{i:0;a:4:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";s:8:"subquery";N;s:4:"used";s:1:"1";}i:1;a:4:{s:4:"name";s:13:"question_type";s:4:"type";s:6:"string";s:8:"subquery";N;s:4:"used";s:1:"1";}}',
            ),
        ));
        
        
    }
}