<?php

use Illuminate\Database\Seeder;

class CmsMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_menus')->delete();
        
        \DB::table('cms_menus')->insert(array (
            0 => 
            array (
                'id' => 3,
                'name' => 'Companies',
                'type' => 'Route',
                'path' => 'AdminCompaniesControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 2,
                'created_at' => '2018-08-27 20:21:07',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'name' => 'Head Trainers',
                'type' => 'Module',
                'path' => 'training_head',
                'color' => 'normal',
                'icon' => 'fa fa-envelope-o',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 7,
                'created_at' => '2018-08-27 20:29:15',
                'updated_at' => '2018-08-27 23:59:17',
            ),
            2 => 
            array (
                'id' => 5,
                'name' => 'Budget',
                'type' => 'Module',
                'path' => 'budget',
                'color' => 'normal',
                'icon' => 'fa fa-money',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 11,
                'created_at' => '2018-08-27 20:32:57',
                'updated_at' => '2018-08-28 00:03:03',
            ),
            3 => 
            array (
                'id' => 6,
                'name' => 'Products',
                'type' => 'Route',
                'path' => 'AdminProductsControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 1,
                'created_at' => '2018-08-27 20:39:19',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'name' => 'Departmets',
                'type' => 'Module',
                'path' => 'departments',
                'color' => 'normal',
                'icon' => 'fa fa-times-circle',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 5,
                'created_at' => '2018-08-27 20:41:47',
                'updated_at' => '2018-08-27 23:59:43',
            ),
            5 => 
            array (
                'id' => 8,
                'name' => 'Skill Sets',
                'type' => 'Module',
                'path' => 'skill_sets',
                'color' => 'normal',
                'icon' => 'fa fa-balance-scale',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 10,
                'created_at' => '2018-08-27 20:57:11',
                'updated_at' => '2018-08-28 00:02:36',
            ),
            6 => 
            array (
                'id' => 9,
                'name' => 'Assessments Types',
                'type' => 'Module',
                'path' => 'assessments',
                'color' => 'normal',
                'icon' => 'fa fa-pencil-square-o',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 6,
                'created_at' => '2018-08-27 21:20:05',
                'updated_at' => '2018-08-28 00:00:22',
            ),
            7 => 
            array (
                'id' => 10,
                'name' => 'Question Bank',
                'type' => 'Module',
                'path' => 'questions',
                'color' => 'normal',
                'icon' => 'fa fa-question',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 8,
                'created_at' => '2018-08-27 21:21:36',
                'updated_at' => '2018-08-28 00:00:47',
            ),
            8 => 
            array (
                'id' => 11,
                'name' => 'Scale Sets',
                'type' => 'Module',
                'path' => 'scale',
                'color' => 'normal',
                'icon' => 'fa fa-square-o',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 9,
                'created_at' => '2018-08-27 21:29:16',
                'updated_at' => '2018-08-28 00:02:13',
            ),
            9 => 
            array (
                'id' => 12,
                'name' => 'Pages',
                'type' => 'Module',
                'path' => 'pages',
                'color' => 'normal',
                'icon' => 'fa fa-pagelines',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 2,
                'created_at' => '2018-08-27 21:48:43',
                'updated_at' => '2018-08-27 23:55:58',
            ),
            10 => 
            array (
                'id' => 13,
                'name' => 'Dashboard',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/dashboard',
                'color' => 'normal',
                'icon' => 'fa fa-dashboard',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 1,
                'id_cms_privileges' => 1,
                'sorting' => 1,
                'created_at' => '2018-08-27 21:51:04',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'Masters',
                'type' => 'URL',
            'path' => 'javascript:void(0)',
                'color' => 'normal',
                'icon' => 'fa fa-search',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 2,
                'created_at' => '2018-08-27 22:31:48',
                'updated_at' => '2018-08-27 22:32:59',
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'CMS',
                'type' => 'URL',
            'path' => 'javascript:void(0)',
                'color' => 'normal',
                'icon' => 'fa fa-arrows',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 3,
                'created_at' => '2018-08-27 23:55:30',
                'updated_at' => '2018-08-27 23:56:38',
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'Assessment Form',
                'type' => 'URL',
                'path' => 'AdminAssessmentsController@getStartForm',
                'color' => 'normal',
                'icon' => 'fa fa-newspaper-o',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 4,
                'created_at' => '2018-08-28 00:07:45',
                'updated_at' => '2018-09-03 17:34:20',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'Job Description',
                'type' => 'Module',
                'path' => 'job_desc',
                'color' => 'normal',
                'icon' => 'fa fa-joomla',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 1,
                'created_at' => '2018-08-28 00:38:11',
                'updated_at' => '2018-08-29 21:13:56',
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'Employee Roles',
                'type' => 'Module',
                'path' => 'employees_types',
                'color' => 'normal',
                'icon' => 'fa fa-search',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 3,
                'created_at' => '2018-08-28 17:42:18',
                'updated_at' => '2018-08-29 19:35:18',
            ),
            16 => 
            array (
                'id' => 19,
                'name' => 'Employee Management',
                'type' => 'Module',
                'path' => 'employees',
                'color' => 'normal',
                'icon' => 'fa fa-users',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 4,
                'created_at' => '2018-08-28 17:44:26',
                'updated_at' => '2018-08-29 19:34:46',
            ),
            17 => 
            array (
                'id' => 21,
                'name' => 'Oranagram Structure',
                'type' => 'Module',
                'path' => 'oranagram_structure',
                'color' => 'normal',
                'icon' => 'fa fa-bar-chart-o',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 13,
                'created_at' => '2018-08-28 21:06:23',
                'updated_at' => '2018-08-29 19:28:12',
            ),
            18 => 
            array (
                'id' => 22,
                'name' => 'Complete Organogram',
                'type' => 'Controller & Method',
                'path' => 'AdminOranagramStructureController@getOrangramAll',
                'color' => 'normal',
                'icon' => 'fa fa-bar-chart',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 13,
                'created_at' => '2018-08-29 18:59:28',
                'updated_at' => '2018-08-29 19:01:06',
            ),
            19 => 
            array (
                'id' => 23,
                'name' => 'Budget Plans',
                'type' => 'Module',
                'path' => 'budget_plans',
                'color' => 'normal',
                'icon' => 'fa fa-money',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 12,
                'created_at' => '2018-08-29 19:46:06',
                'updated_at' => '2018-08-29 20:04:24',
            ),
            20 => 
            array (
                'id' => 24,
                'name' => 'Testimonial',
                'type' => 'Route',
                'path' => 'AdminTestimonialControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 16,
                'created_at' => '2018-08-30 18:18:30',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 25,
                'name' => 'Feature',
                'type' => 'Route',
                'path' => 'AdminFeatureControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 3,
                'created_at' => '2018-08-30 19:35:43',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 26,
                'name' => 'Blog',
                'type' => 'Route',
                'path' => 'AdminBlogControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 15,
                'created_at' => '2018-08-30 19:53:39',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 27,
                'name' => 'Productroadmap',
                'type' => 'Route',
                'path' => 'AdminProductroadmapControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 7,
                'created_at' => '2018-08-30 20:02:25',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 28,
                'name' => 'Whitepaper',
                'type' => 'Route',
                'path' => 'AdminWhitepaperControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 5,
                'created_at' => '2018-08-30 20:08:43',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 29,
                'name' => 'Career',
                'type' => 'Route',
                'path' => 'AdminCareerControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 4,
                'created_at' => '2018-08-30 20:15:03',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 30,
                'name' => 'Contactus',
                'type' => 'Route',
                'path' => 'AdminContactControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 6,
                'created_at' => '2018-08-30 20:22:58',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 31,
                'name' => 'Faqcategory',
                'type' => 'Route',
                'path' => 'AdminFaqcategoryControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 8,
                'created_at' => '2018-08-30 20:34:08',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 32,
                'name' => 'Faqsubcategory',
                'type' => 'Route',
                'path' => 'AdminFaqsubcategoryControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 11,
                'created_at' => '2018-08-30 20:34:47',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 33,
                'name' => 'Faq',
                'type' => 'Route',
                'path' => 'AdminFaqControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 9,
                'created_at' => '2018-08-30 20:35:41',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 34,
                'name' => 'hrindexform',
                'type' => 'Route',
                'path' => 'AdminHrindexFormControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 14,
                'created_at' => '2018-09-03 12:04:00',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'name' => 'Hr Index Question Type',
                'type' => 'Route',
                'path' => 'AdminHrindexQuestionTypeControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 12,
                'created_at' => '2018-09-03 14:54:36',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 36,
                'name' => 'Hr Index Questions',
                'type' => 'Route',
                'path' => 'AdminHrindexQuestionsControllerGetIndex',
                'color' => NULL,
                'icon' => 'fa fa-glass',
                'parent_id' => 15,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 10,
                'created_at' => '2018-09-03 15:04:44',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 37,
                'name' => 'Weightage Management',
                'type' => 'Route',
                'path' => 'AdminWeightAgeControllerGetIndex',
                'color' => 'normal',
                'icon' => 'fa fa-compass',
                'parent_id' => 14,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 14,
                'created_at' => '2018-09-03 16:53:02',
                'updated_at' => '2018-09-03 17:09:42',
            ),
        ));
        
        
    }
}